version: '{build}'
image: Visual Studio 2022
configuration: Release
pull_requests:
  do_not_increment_build_number: true

cache:
  - '%USERPROFILE%\.nuget\packages'

install:
  - ps: choco install gitversion.portable -pre -y

nuget:
  disable_publish_on_pr: true

before_build:
  - ps: dotnet restore src/StringExtensions.Truncate.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value

build:
  project: src/StringExtensions.Truncate.sln
  verbosity: minimal

after_build:
  - cmd: dotnet pack -c %CONFIGURATION% /p:Version="%GitVersion_NuGetVersion%"

artifacts:
  - path: '*.nupkg'
    name: NuGet

deploy:
  - provider: Environment
    name: PreRelease Nuget Feed
    on:
      branch: master
  - provider: Environment
    name: Public Nuget Feed
    on:
      appveyor_repo_tag: true
